train_dataset:
  c4:
    split: train
    num_samples: 51200000 # 1e11 tok ~= 51200000[sa] * 2048[msl] = 200000[ba] * 256[bs] * 2048[msl]
    max_seq_len: 2048
    tokenizer_name: gpt2
    group_method: concat
    seed: 17
    shuffle: true
    drop_last: true
val_dataset:
  c4:
    split: validation
    num_samples: 364608 # approx total validation set
    max_seq_len: 2048
    tokenizer_name: gpt2
    group_method: truncate
    seed: 17
    shuffle: false
    drop_last: false
model:
  gpt2:
    use_pretrained: false
    tokenizer_name: gpt2
    gradient_checkpointing: false
    model_config:
      n_embd: 1024
      n_head: 16
      n_layer: 24
      n_positions: 2048
optimizer:
  decoupled_adamw:
    lr: 3.0e-4
    betas:
      - 0.9
      - 0.95
    eps: 1.0e-08
    weight_decay: 0.0
schedulers:
  - cosine_decay_with_warmup:
      t_warmup: 0.01dur
max_duration: 1ep
train_batch_size: 256 # 0.5e6 tok ~= 256[bs] * 2048[msl]
grad_accum: 16 # 256[bs] / 8[devices] / 2[micro_bs_per_device] = 16[ga], assuming 8xA100-40GB
eval_batch_size: 16 # 8[devices] * 2[micro_bs_per_device] = 16[bs], assuming 8xA100-40GB
seed: 17
device:
  gpu: {}
dataloader:
  pin_memory: true
  persistent_workers: true
  num_workers: 1
  timeout: 0
  prefetch_factor: 2
deepspeed:
  zero_optimization:
    stage: 1
precision: fp16
grad_clip_norm: 1.0
validate_every_n_batches: 1000
validate_every_n_epochs: 1
